application: algobitbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /api/.*
  script: api.app
  
- url: /fetch/.*
  script: fetcher.app
  login: admin
  
- url: /admin/.*
  script: admin.app
  login: admin
  
- url: /.*
  script: pages.app
  

admin_console:
  pages:
  - name: Initialize DB
    url: /admin/dbinit

libraries:
- name: webapp2
  version: latest
- name: jinja2                                                                  
  version: latest